######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 13 15:57:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

OBJECTS_DIR = build
MOC_DIR = build
DESTDIR = bin

# Input
HEADERS += src/MainWindow.h src/ImageProcessor.h
SOURCES += src/main.cpp src/MainWindow.cpp src/ImageProcessor.cpp
